<a href="https://colab.research.google.com/github/tanusreemajumder/Skill-Morph-Assignments/blob/main/assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
# Install required packages (run this first in Google Colab)
!pip install numpy pandas matplotlib

# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)

NumPy version: 2.1.3
Pandas version: 2.2.3


# ** part1: Nampy fandamental**

In [ ]:
# Creating NumPy arrays
arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([[100, 200, 300], [400, 500, 600]])

print("1D Array:", arr1)
print("2D Array:\n", arr2)
print("Array shape:", arr1.shape)
print("Array dtype:", arr1.dtype)

1D Array: [10 20 30 40 50]
2D Array:
 [[100 200 300]
 [400 500 600]]
Array shape: (5,)
Array dtype: int64


# **Array creation function zeros,ones,arange,linspace**

In [ ]:
# Different ways to create arrays
zeros_array = np.zeros((13, 14), dtype = int)

ones_array = np.ones((22, 33), dtype = int)

range_array = np.arange(0, 100, 22)

linspace_array = np.linspace(0, 10, 50)

print("Zeros array:\n", zeros_array)
print("Ones array:\n", ones_array)
print("Range array:", range_array)
print("Linspace array:", linspace_array)

Zeros array:
 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Ones array:
 [[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1

# **Math,Statistic,broadcasting**






In [ ]:
# Mathematical operations on arrays
a = np.array([11, 20, 83, 100, 200])
b = np.array([22, 38, 40, 57, 69])

# Element-wise operations
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Power:", a ** 5)
print("Square root:", np.sqrt(a))

# Statistical operations
print("Mean:", np.mean(a))
print("Standard deviation:", np.std(a))
print("Min:", np.min(a))
print("Max:", np.max(a))

# Broadcasting example
matrix = np.array([[11, 12, 13], [14, 15, 16]])
vector = np.array([100, 200, 300])
result = matrix + vector
print("Broadcasting result:\n", result)

Addition: [ 33  58 123 157 269]
Subtraction: [-11 -18  43  43 131]
Multiplication: [  242   760  3320  5700 13800]
Power: [      161051      3200000   3939040643  10000000000 320000000000]
Square root: [ 3.31662479  4.47213595  9.11043358 10.         14.14213562]
Mean: 82.8
Standard deviation: 68.0158804986012
Min: 11
Max: 200
Broadcasting result:
 [[111 212 313]
 [114 215 316]]


# **Indexing and slicing arrays**

In [ ]:
arr = np.array([101, 201, 301, 401, 501])

# Indexing
print("Element at index 2:", arr[3])

# Slicing
print("Sliced array (from index 1 to 3):", arr[1:4])

# 2D array slicing
arr_2d = np.array([[13, 23, 33], [43, 53, 63], [73, 83, 93]])
print("Sliced 2D array (first two rows):\n", arr_2d[:3])

Element at index 2: 401
Sliced array (from index 1 to 3): [201 301 401]
Sliced 2D array (first two rows):
 [[13 23 33]
 [43 53 63]
 [73 83 93]]


# **Part2: pandas Fundamentals**
creating a dataframe from a dictionary

In [4]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'Martin', 'Moon', 'Piter'],
        'Age': [24, 27, 22, 29, 32, 21],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Las Vegas', 'Atlanta', 'Miami']}

df = pd.DataFrame(data)
print("DataFrame:\n", df)

DataFrame:
       Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3   Martin   29    Las Vegas
4     Moon   32      Atlanta
5    Piter   21        Miami


# **Inspecting a DataFrame — info, describe, head, tail, dtypes**

In [5]:
# Basic DataFrame information
print("\nDataFrame Info:")
print(df.info())
print("\nDataFrame Description:")
print(df.describe())
print("\nDataFrame Shape:", df.shape)
print("Column names:", df.columns.tolist())
# Display first 5 rows
print("First 5 rows of the dataset:")
print(df.head())
# Display last 5 rows
print("\nLast 5 rows of the dataset:")
print(df.tail())
# Check data types
print("\nData Types:")
print(df.dtypes)


DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    6 non-null      object
 1   Age     6 non-null      int64 
 2   City    6 non-null      object
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes
None

DataFrame Description:
             Age
count   6.000000
mean   25.833333
std     4.262237
min    21.000000
25%    22.500000
50%    25.500000
75%    28.500000
max    32.000000

DataFrame Shape: (6, 3)
Column names: ['Name', 'Age', 'City']
First 5 rows of the dataset:
      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3   Martin   29    Las Vegas
4     Moon   32      Atlanta

Last 5 rows of the dataset:
      Name  Age         City
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3   Martin   29    Las Vegas
4     Moon   32      Atlanta
5    Piter   21        Mia

# **Selecting Single & Multiple Columns**

In [10]:
#Accessing a single column
print("Names column:\n", df['Name'])

# Accessing multiple columns
print("\nName and Age columns:\n", df[['Name', 'Age']])

Names column:
 0      Alice
1        Bob
2    Charlie
3     Martin
4       Moon
5      Piter
Name: Name, dtype: object

Name and Age columns:
       Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22
3   Martin   29
4     Moon   32
5    Piter   21


# **Converting a NumPy Array into a DataFrame**

In [12]:
# Convert NumPy array to DataFrame
np_array = np.random.randn(7, 3)
df_from_array = pd.DataFrame(np_array, columns=['A', 'B', 'C'])
print("DataFrame from NumPy array:")
print(df_from_array)

DataFrame from NumPy array:
          A         B         C
0 -0.296355  1.873935  1.419090
1  0.846863  0.059108 -0.111809
2 -0.350613  0.990961  1.855077
3  0.856381 -0.296115  1.923994
4  0.618323  0.171706 -0.862513
5 -0.838327 -0.713585  0.937247
6 -1.880861  0.587165 -1.365177


# **Grouping & Aggregation — Sales by Region**

In [13]:
# Create sample sales data
sales_data = {
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],
    'Product': ['A', 'A', 'B', 'B', 'A', 'B', 'A', 'B'],
    'Sales': [100, 150, 200, 120, 110, 180, 190, 140],
    'Quantity': [10, 15, 20, 12, 11, 18, 19, 14]
}
sales_df = pd.DataFrame(sales_data)
print("Sales DataFrame:")
print(sales_df)

# Group by operations
region_sales = sales_df.groupby('Region')['Sales'].sum()
print("\nSales by Region:")
print(region_sales)

Sales DataFrame:
  Region Product  Sales  Quantity
0  North       A    100        10
1  South       A    150        15
2   East       B    200        20
3   West       B    120        12
4  North       A    110        11
5  South       B    180        18
6   East       A    190        19
7   West       B    140        14

Sales by Region:
Region
East     390
North    210
South    330
West     260
Name: Sales, dtype: int64


# **Working with a Real Dataset**
Loading a CSV from Google Drive

In [14]:
from google.colab import drive
drive.mount('/content/drive')

import warnings
warnings.filterwarnings('ignore')

Mounted at /content/drive


In [19]:
file_path = '/content/drive/MyDrive/diabetes.csv'
df = pd.read_csv(file_path)  # No header in raw CSV
print("Dataset loaded successfully. Shape:", df.shape)

Dataset loaded successfully. Shape: (768, 9)


In [21]:
# Quick overview
print(df.head())
print("\nDataset info:")
print(df.info())

# Basic statistics
print("\nDescriptive statistics:")
print(df.describe())

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  

Dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose       

# ** Checking for Missing Values**

In [22]:
#missing values
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64


In [23]:
file_path = '/content/drive/MyDrive/StudentsPerformance.csv'
df = pd.read_csv(file_path)  # No header in raw CSV
print("Dataset loaded successfully. Shape:", df.shape)

Dataset loaded successfully. Shape: (1000, 8)


In [24]:
# Q1. Display the first 5 rows of the dataset, then print its shape
print("--- First 5 Rows ---")
print(df.head())

print("\n--- Dataset Shape (Rows, Columns) ---")
print(df.shape)

--- First 5 Rows ---
   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75  

--- Dataset Shape (Rows, Columns) ---
(1000, 8)


In [25]:
# Q2. Print the average (mean) math score, reading score and writing score
print("\n--- Average Scores ---")
avg_scores = df[['math score', 'reading score', 'writing score']].mean()
print(avg_scores)


--- Average Scores ---
math score       66.089
reading score    69.169
writing score    68.054
dtype: float64


In [26]:
#missing values
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64
